### ISSUE TITLE
Add 12 Testing Variables to G-Code Analyzer

### ISSUE THREAD

**Issue by medskm** [uwplse/incarnate#9]
Note that these are currently specific to G-Code files produced by Simplify3D
- [ ] Bottom/Top thickness
-- There aren't any single G-Code commands for this, so it's probably going to be calculated from S3D's topSolidLayers, bottomSolidLayers, and layerHeight setting varaibles
- [x] Extruder Temperature
- [x] Extruder Diameter (this is often processed slightly differently than filament diameter)
- [x] Filament Density
- [ ] Flow Rate
-- This rate changes throughout a print, so we need to figure out what we're actually testing for this variable
- [x] Layer height
- [x] Minimal layer time
- [x] Print bed temp
- [x] Retraction distance
- [x] Retraction speed
- [x] Shell thickness
- [x] Travel speed
-- This rate changes throughout a print, so we need to figure out what we're actually testing for this variable

**Comment by marict** [comment]
Implement these is GCode Analyzer instead:
Parameter Name                                                Default Value
1. Reaction Distance (mm)                                 1.50 mm
2. Retraction Speed (mm/min)                           2400 mm/min
3. Primary Layer Height (mm)                            0.1500 mm 
4. Interior Fill Percentage (%)                             20%
5. Primary Extruder Temperature (C)                 230 C
6. Heated Build Platform Temperature (C)        200 C
7. Default Printing Speed (mm/min)                 2500 mm/min  
8. Top Solid Layers (layers)                               4
9. Bottom Solid Layers (layers)                         3
10. Outline/Perimeter Shells (layers)                2
11. Additions (type)                                          Use Skirt/Brim
12. Internal Fill Pattern (type)                           Rectilinear

**Comment by medskm** [comment]
Added! @marict I'm closing this issue, but are you going to be adding this information on the Wiki?
